### ISSUE TITLE
Maximo-returned 400 errors break JSON parsing

### ISSUE THREAD

**Issue by ojw** [sachbalag/ibm-maximo-api#4]
When using the create method to create a new object, Maximo will return a 400 error if some supplied data is invalid.  I would expect this to kick into the deferred object's reject method, but instead CRUDConnector.prototype.__create tries to parse the response as JSON, which it isn't, which causes an error at line 105 in crudconnector.js.

What is the intended functionality of this library if any invalid fields are provided when creating an object in Maximo?

**Comment by sachbalag** [comment]
We are reviewing this issue. This appears to be a bug. An Error response as JSON is expected when invalid fields are provided.

**Comment by sachbalag** [comment]
OJW ... Can you confirm the version of Maximo you are using? It looks like a pretty old one 7.5.0.4 or prior. If that's the case Maximo does not return the error response as JSON. The API code simply writes back whatever Maximo sends us which is probably why it errors out on the JSON.parse() because the older versions of Maximo do not send back a JSON when there is an error. In any case the API codes needs to handle that possibility so we will fix this in the next 48 hours and have a new build up on NPM.

**Comment by ojw** [comment]
I've switched to using a version 7.6.0.3 version of Maximo and am still seeing responses to bad inputs fail to parse.  The console output I see now is:

```
***** RESPONSE 400
undefined:1
Bad Request{"Error":{"message":"BMXAA4190E - Reported Priority 5 is not in the value list.","statusCode":"400","reasonCode":"BMXAA4190E","extendedError":{"moreInfo":{"href":"http:\/\/localhost\/maximo\/oslc\/error\/messages\/BMXAA4190E"}}}}
^

SyntaxError: Unexpected token B
    at Object.parse (native)
    at IncomingMessage.<anonymous> (c:\Users\jorr\code\sidecar\node_modules\ibm-maximo-api\resources\connectors\crudconnector.js:105:20)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

In this case, it looks like the error message is returned as JSON, but has "Bad Request" prepended to the json string.

**Comment by ojw** [comment]
Ah, actually it looks like this  prepending is actually an issue with our IIS configuration - this can probably be closed.

**Comment by ojw** [comment]
Confirmed, when hitting Maximo directly rather than through IIS, the error response is well-formed JSON.

It's not clear to me whether the promise should return a successful value in the case of a 4XX HTTP response vs a rejection - I could see a case that a 400 should follow the `.fail` path instead of `.next`, but that's a separate question, and I don't have a strong feeling either way.
